### ISSUE TITLE
Agila Theme Sidebar Icons

### ISSUE THREAD

**Issue by ghost** [arvi/Agila-Theme#11]
Hello,

I have installed "Agila Theme" successfully but there are some issues like,
1. No sidebar icons - folder icons, file type icons etc.
2. Tab Height is not getting reduced.

I'm sending you the screenshot for your reference.

![agilatheme](https://cloud.githubusercontent.com/assets/14750809/16716048/c5a89e4c-470e-11e6-82aa-038d5e71671e.PNG)

Please help me with this. Thank you :D

**Comment by arvi** [comment]
Hello :smile:

Thanks for reporting. I'll check when I got home (around 8 hours from now :smile: ). I'm currently using Windows 10, Elementary OS (Ubuntu 14.04) and Mac OSX, all with no issue.

**Comment by ghost** [comment]
Okay. 

Thank you :D

**Comment by arvi** [comment]
Hello,

Upon checking, I had no issue [Windows 7 32-bit, Sublime Text 3 Build 3114 (the latest)]. I even tried to copy your settings. 

Here are my suggestions:
- You may want to remove the other "theme" settings on yours since you have two based your  screenshot above in line 2 and line 4. You may copy this, close and open the editor again.

``` json
{
    "color_scheme": "Packages/Agila Theme/Agila Oceanic Next.tmTheme",
    "tab_size": 3,
    "theme": "Agila.sublime-theme",
    "theme_agila_horizontal_spacebar_gray": true,
    "theme_agila_horizontal_spacebar_thinnest": true,
    "theme_agila_sidebar_font_xsmall": true,
    "theme_agila_sidebar_heading_lightblue": true,
    "theme_agila_sidebar_light_icons": true,
    "theme_agila_sidebar_small": true,
    "theme_agila_vertical_spacebar_gray": true,
    "theme_agila_vertical_spacebar_thinnest": true,
    "indent_guide_options": [ "draw_normal", "draw_active"],
    "theme_agila_compact_tab": true     
}
```

![st3-windows7-32bit](https://cloud.githubusercontent.com/assets/653750/16787676/954ea318-48d0-11e6-9f98-ba56cff7586e.png)
- Check your Sublime build and version (Agila theme is for Sublime Text 3 only)
- Uninstall Agila Theme and install again

Thanks :smile:

**Comment by ghost** [comment]
It's working fine. Thank you :+1:
