### ISSUE TITLE
feature request - port to jetbrains ide

### ISSUE THREAD

**Issue by misterlami** [arvi/Agila-Theme#16]
Port Agilia to work with IDE's from Jetbrains.

**Comment by arvi** [comment]
Hello @mrlami, that'd be great idea even porting it to Atom. However, I can't make time to study how to do such since I'm focusing on improving my development skills.

After some quick research, it's possible to port Agila tmThemes to JetBrains. You can download Agila theme and try importing the .tmTheme.
- https://www.jetbrains.com/help/phpstorm/2016.2/textmate-bundles.html
- http://stackoverflow.com/questions/8506413/is-it-possible-to-import-textmate-themes-to-intellij-idea
- https://github.com/equinusocio/material-theme/issues/160

If you're successful in your experiment, you may want to do a pull request here and contribute your work. Good luck. 😄
