### ISSUE TITLE
For other ed

### ISSUE THREAD

**Issue by Alexey-T** [arvi/Agila-Theme#2]
Hi, good theme. Possible to 'port' to CudaText maybe?

**Comment by arvi** [comment]
Thanks :)

Just found out about CudaText editor since you mentioned it. Anyways, I've looked at their docs and couldn't find a theming section or any github repo related to theming I can inspect to base the porting to. If you know any repo then maybe we can look at it or you can just fork my repo and try to experiment on how to go about it. :)

**Comment by Alexey-T** [comment]
The inf about making thm-> http://wiki.freepascal.org/CudaText#How_to_make_theme_package

**Comment by arvi** [comment]
Hey @Alexey-T, sorry I can't make time to study how to do such since I'm focusing on improving my development skills. If you want you can fork Agila and experiment on your own. 😄
