### ISSUE TITLE
Disable default icons

### ISSUE THREAD

**Issue by d8vjork** [arvi/Agila-Theme#38]
Hi there,

I like this theme, I prefer it instead Material or any other, my thing is: Is there a way to disable the built-in icons or override them? I'm using A File Icon which seems pretty good.

PD: I think the best thing is just override folder icons and let the others by default or ready to override by the user (using another package)

**Comment by arvi** [comment]
Hello @d8vjork,

Thank you for your compliments. I’m glad you liked it as much as I did.

I haven’t updated this theme for a long time due to workload and other stuff.

You can still customize this for your liking by setting content_margin to 0 on the icons you don’t want to see.

Source: https://forum.sublimetext.com/t/how-to-remove-sidebar-icons-build-3065/13760/42

**Comment by d8vjork** [comment]
Ok, my fault, this did the trick:

![image](https://user-images.githubusercontent.com/2331052/54083942-68571f80-4322-11e9-999b-b16eb908312e.png)
