### ISSUE TITLE
padding issues on side menu items

### ISSUE THREAD

**Issue by misterlami** [arvi/Agila-Theme#5]
compare below...

![image](https://cloud.githubusercontent.com/assets/1946090/14928792/04aba460-0e28-11e6-8328-5877646db5e9.png)

**Comment by arvi** [comment]
@mrlami hmmmm the extra padding was intentional to make the directory tree obvious on a glance. As you can see your right screenshot, it's confusing if it's under "1-working" directory or not. :smile:

**Comment by misterlami** [comment]
@arvi interesting...  It actually is confusing to me the way it currently is.  Adding an optional setting to remove the extra padding would be nice.

**Comment by arvi** [comment]
@mrlami I see. Okies, I'll reopen the issue and include your request on next release. :smile:

**Comment by misterlami** [comment]
Awesome...  TY!

**Comment by arvi** [comment]
Hello. Sorry I can't apply this change since it has issue with parent directory file siblings. 😅 

As you can see in the screenshot, removing the indent just aligned the file sibling with the parent's children files.

But if you really want to, you can fork agila theme and play around with the sidebar_tree option. I've tried a lot of combinations and the result is the same.

![screen shot 2016-05-21 at 2 23 42 am](https://cloud.githubusercontent.com/assets/653750/15437708/372ab49c-1efb-11e6-9ac3-002bf6346197.png)

**Comment by arvi** [comment]
I can't get this off my mind so I decided to study how others do it. :smile:

Finally! I will include this on my next commit.

![screen shot 2016-05-21 at 10 39 06 am](https://cloud.githubusercontent.com/assets/653750/15445945/75583e34-1f40-11e6-89c0-09f287482c29.png)

**Comment by arvi** [comment]
Done :smile: Thanks for your suggestion.

`"theme_agila_compact_sidebar": true,`

https://github.com/arvi/Agila-Theme/commit/465e2352a4f3c646510e25a6ce5047379283a491

**Comment by misterlami** [comment]
Nice...  TY!
